### 모델 검증을 위한 추가 데이터 수집 및 전처리
대상지역 : 광명시\
    - 성남시와 동일한 구조의 데이터를 구할 수 있어 광명시를 선택하였음.\
9ai037 이지원

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### 1. 초등학교현황 -> 어린이 보호구역 현황 데이터 사용
Raw-Data\0. 스쿨존목록\광명시_어린이보호구역정보.csv\
출처: https://www.data.go.kr/data/15098271/fileData.do?recommendDataYn=Y\
날짜 기준: 20211126

In [8]:
school_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\0. 스쿨존목록\광명시_어린이보호구역정보.csv', encoding='cp949')

# 데이터프레임 정보 확인 ---- 결측치 없음
school_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   보호구역아이디   49 non-null     int64
 1   시설종류      49 non-null     object
 2   대상시설명     49 non-null     object
 3   소재지도로명주소  49 non-null     object
 4   소재지지번주소   49 non-null     object
 5   경도        49 non-null     float64
 6   위도        49 non-null     float64
 7   관리기관명     49 non-null     object
 8   관할경찰서명    49 non-null     object
 9   cctv설치여부  49 non-null     object
 10  cctv설치대수  49 non-null     int64
 11  보호구역 도로폭  49 non-null     int64
 12  데이터기준일자   49 non-null     object
 13  지정일자      49 non-null     object
dtypes: float64(2), int64(3), object(9)
memory usage: 5.5+ KB

In [9]:
# 시설 종류, 대상시설명, 도로명주소, 지번주소, 위도, 경도만 추출
school_df = school_df[['보호구역아이디','시설종류', '대상시설명', '소재지도로명주소', '소재지지번주소', '위도', '경도', '보호구역 도로폭']]
school_df = school_df.astype({'위도': 'float64', '경도': 'float64'}, errors='ignore')
school_df.head()

,보호구역아이디,시설종류,대상시설명,소재지도로명주소,소재지지번주소,위도,경도,보호구역 도로폭
0,25,초등학교,빛가온초등학교,경기도 광명시 양달로10번길 8,경기도 광명시 일직동 377,37.413690,126.882026,12
1,39,유치원,빛가온유치원,경기도 광명시 새빛공원로 54,경기도 광명시 일직동 517-4,37.416952,126.888265,14
2,49,어린이집,광명생명숲어린이집,경기도 광명시 성채로78번길 5,경기도 광명시 소하동 1385,37.432309,126.877817,20
3,51,어린이집,큰별어린이집,경기도 광명시 영당안로 43,경기도 광명시 소하동 937,37.436146,126.877327,10
4,24,초등학교,충현초등학교,경기도 광명시 성채안로 16,경기도 광명시 소하동 1375,37.432490,126.884627,19

In [10]:
school_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\0_gwangmyung_school_zone.csv', index=False, encoding='cp949')

### 2. 광명시 인구및세대 현황
Raw-Data\광명_202512_202512_연령별인구현황_연간.csv\
출처: https://jumin.mois.go.kr/ageStatMonth.do\
행정구역: 경기도 광명시
기간: 연간 / 2025년 - 2025년\
연령구분단위: 5세\
연령조회범위: 0세 ~ 100세

In [11]:
import pandas as pd
population_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\광명_202512_202512_연령별인구현황_연간.csv', encoding='cp949')
population_df.info()
population_df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 70 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   행정구역             20 non-null     object
 1   2025년_계_총인구수     20 non-null     object
 2   2025년_계_연령구간인구수  20 non-null     object
 3   2025년_계_0~4세     20 non-null     object
 4   2025년_계_5~9세     20 non-null     object
 5   2025년_계_10~14세   20 non-null     object
 6   2025년_계_15~19세   20 non-null     object
 7   2025년_계_20~24세   20 non-null     object
 8   2025년_계_25~29세   20 non-null     object
 9   2025년_계_30~34세   20 non-null     object
 10  2025년_계_35~39세   20 non-null     object
 11  2025년_계_40~44세   20 non-null     object
 12  2025년_계_45~49세   20 non-null     object
 13  2025년_계_50~54세   20 non-null     object
 14  2025년_계_55~59세   20 non-null     object
 15  2025년_계_60~64세   20 non-null     object
 16  2025년_계_65~69세   20 non-null     object
 17  2025년_계_70~74세   20 non-null     object
 18  2025년_계_75~79세   20 non-null     object
 19  2025년_계_80~84세   20 non-null     object
 20  2025년_계_85~89세   20 non-null     object
 21  2025년_계_90~94세   20 non-null     object
 22  2025년_계_95~99세   20 non-null     int64
 23  2025년_계_100세 이상  20 non-null     int64
 24  2025년_남_총인구수     20 non-null     object
 25  2025년_남_연령구간인구수  20 non-null     object
 26  2025년_남_0~4세     20 non-null     object
 27  2025년_남_5~9세     20 non-null     object
 28  2025년_남_10~14세   20 non-null     object
 29  2025년_남_15~19세   20 non-null     object
 30  2025년_남_20~24세   20 non-null     object
 31  2025년_남_25~29세   20 non-null     object
 32  2025년_남_30~34세   20 non-null     object
 33  2025년_남_35~39세   20 non-null     object
 34  2025년_남_40~44세   20 non-null     object
 35  2025년_남_45~49세   20 non-null     object
 36  2025년_남_50~54세   20 non-null     object
 37  2025년_남_55~59세   20 non-null     object
 38  2025년_남_60~64세   20 non-null     object
 39  2025년_남_65~69세   20 non-null     object
 40  2025년_남_70~74세   20 non-null     object
 41  2025년_남_75~79세   20 non-null     object
 42  2025년_남_80~84세   20 non-null     object
 43  2025년_남_85~89세   20 non-null     object
 44  2025년_남_90~94세   20 non-null     int64
 45  2025년_남_95~99세   20 non-null     int64
 46  2025년_남_100세 이상  20 non-null     int64
 47  2025년_여_총인구수     20 non-null     object
 48  2025년_여_연령구간인구수  20 non-null     object
 49  2025년_여_0~4세     20 non-null     object
 50  2025년_여_5~9세     20 non-null     object
 51  2025년_여_10~14세   20 non-null     object
 52  2025년_여_15~19세   20 non-null     object
 53  2025년_여_20~24세   20 non-null     object
 54  2025년_여_25~29세   20 non-null     object
 55  2025년_여_30~34세   20 non-null     object
 56  2025년_여_35~39세   20 non-null     object
 57  2025년_여_40~44세   20 non-null     object
 58  2025년_여_45~49세   20 non-null     object
 59  2025년_여_50~54세   20 non-null     object
 60  2025년_여_55~59세   20 non-null     object
 61  2025년_여_60~64세   20 non-null     object
 62  2025년_여_65~69세   20 non-null     object
 63  2025년_여_70~74세   20 non-null     object
 64  2025년_여_75~79세   20 non-null     object
 65  2025년_여_80~84세   20 non-null     object
 66  2025년_여_85~89세   20 non-null     object
 67  2025년_여_90~94세   20 non-null     int64
 68  2025년_여_95~99세   20 non-null     int64
 69  2025년_여_100세 이상  20 non-null     int64
dtypes: int64(8), object(62)
memory usage: 11.1+ KB

,행정구역,2025년_계_총인구수,2025년_계_연령구간인구수,2025년_계_0~4세,2025년_계_5~9세,2025년_계_10~14세,2025년_계_15~19세,2025년_계_20~24세,2025년_계_25~29세,2025년_계_30~34세,...,2025년_여_55~59세,2025년_여_60~64세,2025년_여_65~69세,2025년_여_70~74세,2025년_여_75~79세,2025년_여_80~84세,2025년_여_85~89세,2025년_여_90~94세,2025년_여_95~99세,2025년_여_100세 이상
0,경기도 광명시 (4121000000),"293,947","293,947","8,285","9,838","13,384","14,526","14,646","18,048","22,049",...,"12,471","11,408","11,158","7,417","4,960","3,617","2,178",984,228,38
1,경기도 광명시 광명1동(4121051000),"9,919","9,919",546,380,377,351,438,599,"1,190",...,398,300,242,160,90,56,42,8,2,0
2,경기도 광명시 광명2동(4121052000),"5,637","5,637",174,127,129,209,232,357,498,...,237,243,265,162,125,93,47,18,1,0

In [12]:
# dtype = object인 모든 숫자열을 숫자형으로 변환

id_cols = ['행정구역']
num_cols = population_df.columns.difference(id_cols)

population_df[num_cols] = (
    population_df[num_cols]
    .replace(',', '', regex=True)
    .apply(pd.to_numeric)
)

In [13]:
# 행정구역에서 'ㅇㅇㅇ동' 발라내기
population_df['동'] = population_df['행정구역'].str.extract(r'(\S+동)')

population_df = population_df[['동','2025년_계_총인구수','2025년_계_0~4세','2025년_계_5~9세','2025년_계_10~14세']]
population_df.head(3)

      동  2025년_계_총인구수  2025년_계_0~4세  2025년_계_5~9세  2025년_계_10~14세
0   NaN        293947          8285          9838           13384
1  광명1동          9919           546           380             377
2  광명2동          5637           174           127             129

In [14]:
# '동' 열에 결측치가 있는 행 제거   
population_df = population_df.dropna(subset=['동'])

# 컬럼 이름 변경
population_df = population_df.rename(columns={
    '2025년_계_총인구수': '총인구수',
    '2025년_계_0~4세': '0~4세',
    '2025년_계_5~9세': '5~9세',
    '2025년_계_10~14세': '10~14세'
})

population_df

       동   총인구수  0~4세  5~9세  10~14세
1   광명1동   9919   546   380     377
2   광명2동   5637   174   127     129
3   광명3동   9083    82   108     196
4   광명4동   7260   148   127     176
5   광명5동  11379   214   253     424
6   광명6동  12496   386   459     610
7   광명7동  25355   935   887     979
8   철산1동  10090   293   297     508
9   철산2동  15169   667   621     604
10  철산3동  35277   976  1566    2179
11  철산4동   8972   318   303     375
12  하안1동  24348   498   913    1485
13  하안2동  12530   294   303     324
14  하안3동  18216   504   464     595
15  하안4동  11275   294   310     414
16  소하1동  29090   649  1130    1763
17  소하2동  25055   440   595     959
18   일직동  21148   851   979    1264
19   학온동   1648    16    16      23

In [15]:
#어린이 총인구 컬럼 추가
population_df['어린이 총인구'] = population_df['0~4세'] + population_df['5~9세'] + population_df['10~14세']

In [16]:
# 광명1동~광명7동, 철산1동~철산4동, 하안1동~하안3동, 소하1동~소하2동 을 광명동, 철산동, 하안동, 소하동으로 통합
import re

population_df['행정동_그룹'] = population_df['동'].str.replace(r'\d+동$', '동', regex=True)

#행정동별로 합산
agg_df = (
    population_df
        .groupby('행정동_그룹', as_index=False)
        .agg({
            '총인구수': 'sum',
            '0~4세': 'sum',
            '5~9세': 'sum',
            '10~14세': 'sum',
            '어린이 총인구': 'sum'
        })
)

#어린이 비율 계산

agg_df['어린이 비율(%)'] = (
    agg_df['어린이 총인구'] / agg_df['총인구수'] * 100
)

#정렬
agg_df = agg_df.sort_values('행정동_그룹').reset_index(drop=True)

In [17]:
agg_df = agg_df.rename(columns={'행정동_그룹': '동'})

In [ ]:
agg_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\1_gwangmyung_population.csv', index=False, encoding='cp949')

### 3. 광명시 사고데이터 정리
2020 ~ 2024 \
Raw-Data\스쿨존 사고데이터\스쿨존어린이사고다발지현황.csv

In [19]:
import pandas as pd
acc = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존 사고데이터\스쿨존어린이사고다발지현황.csv', encoding='cp949')
acc.info()
acc.head(3)
acc.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   시군명          95 non-null     object
 1   구/읍면동명       95 non-null     object
 2   사고년도         95 non-null     int64
 3   사고유형구분       95 non-null     object
 4   다발지역FID      95 non-null     int64
 5   다발지역ID       95 non-null     int64
 6   법정동코드        95 non-null     int64
 7   위치코드         95 non-null     int64
 8   시도시군구명       95 non-null     object
 9   사고지역위치명      95 non-null     object
 10  발생건수         95 non-null     int64
 11  사상자수         95 non-null     int64
 12  사망자수         95 non-null     int64
 13  중상자수         95 non-null     int64
 14  경상자수         95 non-null     int64
 15  부상자수         95 non-null     int64
 16  위도           95 non-null     float64
 17  경도           95 non-null     float64
 18  사고다발지역폴리곤정보  95 non-null     object
dtypes: float64(2), int64(11), object(6)
memory usage: 14.2+ KB

Index(['시군명', '구/읍면동명', '사고년도', '사고유형구분', '다발지역FID', '다발지역ID', '법정동코드', '위치코드',
       '시도시군구명', '사고지역위치명', '발생건수', '사상자수', '사망자수', '중상자수', '경상자수', '부상자수',
       '위도', '경도', '사고다발지역폴리곤정보'],
      dtype='object')

In [20]:
acc = acc[acc['시군명'].str.contains('광명')]
acc = acc[['시군명', '구/읍면동명', '사고년도','발생건수', '사상자수', '사망자수', '중상자수', '경상자수', '부상자수', '위도', '경도']]
acc.head(3)

,시군명,구/읍면동명,사고년도,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
6,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778
8,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778
24,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778

In [21]:
#전국교통사고다발지역표준데이터 전처리
acc2 = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존 사고데이터\전국교통사고다발지역표준데이터.csv', encoding='cp949')
acc2.columns

Index(['사고지역관리번호', '사고연도', '사고유형구분', '위치코드', '사고다발지역시도시군구', '사고지역위치명', '사고건수',
       '사상자수', '사망자수', '중상자수', '경상자수', '부상신고자수', '위도', '경도', '사고다발지역폴리곤정보',
       '데이터기준일자', '제공기관코드', '제공기관명'],
      dtype='object')

In [22]:
acc2 = acc2[acc2['사고다발지역시도시군구'].str.contains('광명')]
acc2 = acc2[acc2['사고유형구분'].str.contains('어린이')]
acc2['구/읍면동명'] = acc2['사고지역위치명'].str.extract(r'\s([^\s()]+동)\(')
acc2['보호구역명'] = acc2['사고지역위치명'].str.extract(r'\(([^)]+ )\부근')
acc2 = acc2[['사고다발지역시도시군구','구/읍면동명','보호구역명','사고연도','사고건수','사상자수', '사망자수', '중상자수', '경상자수', '부상신고자수', '위도', '경도']]
acc2 = acc2.rename(columns={'사고다발지역시도시군구': '시군명', '사고연도': '사고년도', '사고건수': '발생건수', '부상신고자수': '부상자수'})
acc2.head(3)

,시군명,구/읍면동명,보호구역명,사고년도,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도
2499,경기도 광명시1,철산동,광명북초교,2021,2,2,0,1,1,0,37.489097,126.867778
5310,경기도 광명시1,철산동,광북초교사거리,2018,3,3,0,1,1,1,37.487164,126.867710
6367,경기도 광명시1,광명동,광문초교사거리,2017,4,5,0,1,3,1,37.468584,126.852059

In [23]:
#스쿨존 내 사고 다발지와 전국교통사고다발지역표준데이터의 사고 다발지 합치기    
acc_combined = pd.concat([acc, acc2.drop(columns=['보호구역명'])], ignore_index=True)
#위도, 경도, 사고년도 기준으로 중복 제거
acc_combined = acc_combined.drop_duplicates(subset=['위도', '경도', '사고년도']).reset_index(drop=True)
acc_combined.head(3)

   시군명 구/읍면동명  사고년도  발생건수  사상자수  사망자수  중상자수  경상자수  부상자수         위도          경도
0  광명시    철산동  2021     2     2     0     1     1     0  37.489097  126.867778
1  광명시    철산동  2016     2     2     0     2     0     0  37.488157  126.867872
2  광명시    소하동  2015     2     2     0     1     1     0  37.434257  126.885246

In [24]:
# 위도 경도에 맞춰 인근 어린이보호구역 매칭하기

# 필요 함수
# 1. 두 좌표 간 거리 계산 함수
import glob
import os

def haversine_m(lat1, lon1, lat2, lon2):
    """
    두 좌표 사이의 거리를 미터(m) 단위로 반환.
    지구를 구체로 가정하는 Haversine 공식 사용.
    """
    R = 6371000  # 지구 반경 (미터)
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    return R * 2 * np.arcsin(np.sqrt(a))

acc_coordinates = acc_combined[['위도', '경도']].drop_duplicates()
school_coordinates = school_df[['대상시설명','위도', '경도']].drop_duplicates()

matched_zones = []
for _, acc_row in acc_coordinates.iterrows():
    for _, school_row in school_coordinates.iterrows():
        distance = haversine_m(acc_row['위도'], acc_row['경도'], school_row['위도'], school_row['경도'])
        if distance <= 300:  # 300m 이내인 경우
            matched_zones.append({
                '사고위도': acc_row['위도'],
                '사고경도': acc_row['경도'],
                '보호구역명': school_row['대상시설명']
            })

matched_df = pd.DataFrame(matched_zones)
matched_df.head(3)

        사고위도        사고경도    보호구역명
0  37.489097  126.867778    예지유치원
1  37.489097  126.867778  광명북초등학교
2  37.488157  126.867872    예지유치원

In [25]:
#사고위도와 사고경도를 기준으로 보호구역명 매칭 결과를 acc_combined에 병합
acc_combined = acc_combined.merge(matched_df, left_on=['위도', '경도'], right_on=['사고위도', '사고경도'], how='left')
acc_combined = acc_combined.drop(columns=['사고위도', '사고경도'])
acc_combined.head(3)

,시군명,구/읍면동명,사고년도,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,보호구역명
0,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778,예지유치원
1,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778,광명북초등학교
2,광명시,철산동,2016,2,2,0,2,0,0,37.488157,126.867872,예지유치원

In [26]:
acc_combined.info()
acc_combined[acc_combined.isna().any(axis=1)]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시군명     25 non-null     object
 1   구/읍면동명  25 non-null     object
 2   사고년도    25 non-null     int64
 3   발생건수    25 non-null     int64
 4   사상자수    25 non-null     int64
 5   사망자수    25 non-null     int64
 6   중상자수    25 non-null     int64
 7   경상자수    25 non-null     int64
 8   부상자수    25 non-null     int64
 9   위도      25 non-null     float64
 10  경도      25 non-null     float64
 11  보호구역명   24 non-null     object
dtypes: float64(2), int64(7), object(3)
memory usage: 2.5+ KB

,시군명,구/읍면동명,사고년도,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,보호구역명
16,경기도 광명시1,광명동,2015,5,5,0,1,4,0,37.473344,126.854538,NaN

In [27]:
acc_combined

,시군명,구/읍면동명,사고년도,발생건수,사상자수,사망자수,중상자수,경상자수,부상자수,위도,경도,보호구역명
0,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778,예지유치원
1,광명시,철산동,2021,2,2,0,1,1,0,37.489097,126.867778,광명북초등학교
2,광명시,철산동,2016,2,2,0,2,0,0,37.488157,126.867872,예지유치원
3,광명시,철산동,2016,2,2,0,2,0,0,37.488157,126.867872,광명북초등학교
4,광명시,소하동,2015,2,2,0,1,1,0,37.434257,126.885246,충현초등학교
5,광명시,소하동,2015,2,2,0,1,1,0,37.434257,126.885246,트인아이유치원
6,경기도 광명시1,철산동,2021,2,2,0,1,1,0,37.489097,126.867778,예지유치원
7,경기도 광명시1,철산동,2021,2,2,0,1,1,0,37.489097,126.867778,광명북초등학교
8,경기도 광명시1,철산동,2018,3,3,0,1,1,1,37.487164,126.867710,광명북초등학교
9,경기도 광명시1,광명동,2017,4,5,0,1,3,1,37.468584,126.852059,예림유치원
10,경기도 광명시1,광명동,2017,4,5,0,1,3,1,37.468584,126.852059,광문초등학교
11,경기도 광명시1,철산동,2016,4,4,0,0,4,0,37.485841,126.863637,광명동초등학교
12,경기도 광명시1,철산동,2016,2,2,0,2,0,0,37.488157,126.867872,예지유치원
13,경기도 광명시1,철산동,2016,2,2,0,2,0,0,37.488157,126.867872,광명북초등학교
14,경기도 광명시2,광명동,2015,3,3,0,0,2,1,37.481507,126.856122,녹야유치원
15,경기도 광명시2,광명동,2015,3,3,0,0,2,1,37.481507,126.856122,광명초등학교
16,경기도 광명시1,광명동,2015,5,5,0,1,4,0,37.473344,126.854538,NaN
17,경기도 광명시1,소하동,2015,2,2,0,1,1,0,37.434257,126.885246,충현초등학교
18,경기도 광명시1,소하동,2015,2,2,0,1,1,0,37.434257,126.885246,트인아이유치원
19,경기도 광명시1,광명동,2014,5,5,0,3,2,0,37.473862,126.848961,엄지창의어린이집
20,경기도 광명시1,광명동,2013,3,4,0,1,3,0,37.475294,126.847943,엄지창의어린이집
21,경기도 광명시1,광명동,2013,3,4,0,1,3,0,37.475294,126.847943,광명서초등학교
22,경기도 광명시1,소하동,2012,3,3,0,0,3,0,37.436492,126.879981,큰별어린이집
23,경기도 광명시1,소하동,2012,3,3,0,0,3,0,37.436492,126.879981,아란유치원
24,경기도 광명시1,소하동,2012,3,3,0,0,3,0,37.436492,126.879981,서면초등학교

In [28]:
# 결측치 처리 - 보호구역명 결측치는 '보호구역명 없음'으로 대체
acc_combined['보호구역명'] = acc_combined['보호구역명'].fillna('보호구역명 없음')

# 2020~2024년 사고 데이터만 남기기
acc_combined = acc_combined[acc_combined['사고년도'] >= 2020]
acc_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 7
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시군명     4 non-null      object
 1   구/읍면동명  4 non-null      object
 2   사고년도    4 non-null      int64
 3   발생건수    4 non-null      int64
 4   사상자수    4 non-null      int64
 5   사망자수    4 non-null      int64
 6   중상자수    4 non-null      int64
 7   경상자수    4 non-null      int64
 8   부상자수    4 non-null      int64
 9   위도      4 non-null      float64
 10  경도      4 non-null      float64
 11  보호구역명   4 non-null      object
dtypes: float64(2), int64(7), object(3)
memory usage: 416.0+ bytes

In [29]:
acc_combined.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\1_gwangmyung_accidents.csv', index=False, encoding='cp949')

### 4. 시설물 전처리
CCTV: https://www.data.go.kr/data/15098257/fileData.do\
교통단속카메라: https://www.data.go.kr/data/15098263/fileData.do\
과속방지턱: https://www.data.go.kr/data/15098261/fileData.do\
신호등: https://www.data.go.kr/data/15098258/fileData.do\
횡단보호: https://www.data.go.kr/data/15098260/fileData.do\
보호구역 내 안전표지: https://www.data.go.kr/data/15098264/fileData.do\
옐로카펫: https://www.data.go.kr/data/15098266/fileData.do\
무단횡단방지펜스: https://www.data.go.kr/data/15098269/fileData.do\
도로적색표면: https://www.data.go.kr/data/15098265/fileData.do\
데이터날짜기준 20220118

In [30]:
# cctv 정보
cctv_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내cctv정보.csv', encoding='cp949')
cctv_df.info()
cctv_df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SFZN_ID     98 non-null     int64
 1   INST_NM     98 non-null     object
 2   RDNMADR     98 non-null     object
 3   LNMADR      98 non-null     object
 4   INST_PURPS  98 non-null     object
 5   CCTV_CNT    98 non-null     int64
 6   CCTV_PIXEL  98 non-null     int64
 7   PTGRF_INFO  98 non-null     object
 8   CSTDY_DAY   0 non-null      float64
 9   INST_YYMM   0 non-null      float64
 10  PH_NUMBER   98 non-null     int64
 11  경도          98 non-null     float64
 12  위도          98 non-null     float64
 13  REF_DATE    98 non-null     object
 14  ID_PRT      98 non-null     object
dtypes: float64(4), int64(4), object(7)
memory usage: 11.6+ KB

,SFZN_ID,INST_NM,RDNMADR,LNMADR,INST_PURPS,CCTV_CNT,CCTV_PIXEL,PTGRF_INFO,CSTDY_DAY,INST_YYMM,PH_NUMBER,경도,위도,REF_DATE,ID_PRT
0,20,광명시,경기도 광명시 안현로 80-2,경기도 광명시 하안동 25-1,어린이보호,1,0,360도전방면,NaN,NaN,182,126.881458,37.465623,2021-10-01,0020-V-0001
1,21,광명시,경기도 광명시 소하일로 45,경기도 광명시 소하동 1328,다목적,1,0,360도전방면,NaN,NaN,182,126.888017,37.448624,2021-10-26,0021-V-0003
2,11,광명시,경기도 광명시 금당로 11-7,경기도 광명시 하안동 297,다목적,4,0,360도전방면,NaN,NaN,182,126.880495,37.457696,2021-10-14,0011-V-0001

In [31]:
cctv_df.columns

Index(['SFZN_ID', 'INST_NM', 'RDNMADR', 'LNMADR', 'INST_PURPS', 'CCTV_CNT',
       'CCTV_PIXEL', 'PTGRF_INFO', 'CSTDY_DAY', 'INST_YYMM', 'PH_NUMBER', '경도',
       '위도', 'REF_DATE', 'ID_PRT'],
      dtype='object')

In [32]:
cctv_df = cctv_df[['ID_PRT','위도','경도','INST_PURPS']]
cctv_df['카테고리'] = '생활안전CCTV'
cctv_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_cctv.csv', index=False, encoding='cp949')

In [33]:
#횡단보도 전처리
crosswalk_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내횡단보도정보.csv', encoding='cp949')
crosswalk_df.info()
crosswalk_df.head(3)
crosswalk_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   보호구역 아이디    320 non-null    int64
 1   시도명         320 non-null    object
 2   시군구명        320 non-null    object
 3   도로명         320 non-null    object
 4   소재지도로명주소    320 non-null    object
 5   소재지지번주소     320 non-null    object
 6   관리번호        320 non-null    object
 7   횡단보도종류      320 non-null    int64
 8   자전거횡단도겸용여부  320 non-null    object
 9   고원식 적용여부    320 non-null    object
 10  경도          320 non-null    float64
 11  위도          320 non-null    float64
 12  차로수         320 non-null    int64
 13  횡단보도폭       320 non-null    int64
 14  횡단보도연장      320 non-null    int64
 15  보행자신호등유무    320 non-null    object
 16  보행자작동신호기유무  320 non-null    object
 17  음향신호기설치여부   320 non-null    object
 18  녹색신호시간      320 non-null    int64
 19  적색신호시간      320 non-null    int64
 20  교통섬유무       320 non-null    object
 21  보도턱낮춤여부     320 non-null    object
 22  점자블록유무      320 non-null    object
 23  집중조명시설유무    320 non-null    object
 24  관리기관명       320 non-null    object
 25  관리기관 전화번호   320 non-null    int64
 26  데이터기준일자     320 non-null    object
dtypes: float64(2), int64(8), object(17)
memory usage: 67.6+ KB

Index(['보호구역 아이디', '시도명', '시군구명', '도로명', '소재지도로명주소', '소재지지번주소', '관리번호',
       '횡단보도종류', '자전거횡단도겸용여부', '고원식 적용여부', '경도', '위도', '차로수', '횡단보도폭',
       '횡단보도연장', '보행자신호등유무', '보행자작동신호기유무', '음향신호기설치여부', '녹색신호시간', '적색신호시간',
       '교통섬유무', '보도턱낮춤여부', '점자블록유무', '집중조명시설유무', '관리기관명', '관리기관 전화번호',
       '데이터기준일자'],
      dtype='object')

In [34]:
crosswalk_df = crosswalk_df[['관리번호','위도','경도','차로수']]
crosswalk_df['카테고리'] = '횡단보도'
crosswalk_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_crosswalk.csv', index=False, encoding='cp949')

In [35]:
# 옐로카펫 전처리
yellow_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내옐로우카펫정보.csv', encoding='cp949')
yellow_df.info()
yellow_df.head(3)
yellow_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   보호구역아이디  20 non-null     int64
 1   시도명      20 non-null     object
 2   시군구명     20 non-null     object
 3   읍면동명     20 non-null     object
 4   관리번호     20 non-null     object
 5   교육시설명    20 non-null     object
 6   관할경찰서명   20 non-null     object
 7   경도       20 non-null     float64
 8   위도       20 non-null     float64
 9   데이터기준일자  20 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 1.7+ KB

Index(['보호구역아이디', '시도명', '시군구명', '읍면동명', '관리번호', '교육시설명', '관할경찰서명', '경도', '위도',
       '데이터기준일자'],
      dtype='object')

In [36]:
yellow_df = yellow_df[['관리번호','위도','경도','교육시설명']]
yellow_df['카테고리'] = '옐로카펫'
yellow_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_yellow_carpet.csv', index=False, encoding='cp949')

In [37]:
# 신호등 전처리
signal_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내신호등정보.csv', encoding='cp949') 
signal_df.info()
signal_df.head(3)
signal_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   보호구역 아이디       613 non-null    int64
 1   시군구명           613 non-null    object
 2   도로종류           613 non-null    object
 3   도로노선번호         0 non-null      float64
 4   도로노선명          613 non-null    object
 5   도로노선방향         613 non-null    object
 6   소재지도로명주소       613 non-null    object
 7   소재지지번주소        613 non-null    object
 8   경도             613 non-null    float64
 9   위도             613 non-null    float64
 10  신호기설치방식        613 non-null    int64
 11  도로형태           613 non-null    int64
 12  주도로여부          613 non-null    object
 13  관리번호           613 non-null    object
 14  신호등구분          613 non-null    int64
 15  신호등색종류         613 non-null    int64
 16  신호등화방식         613 non-null    int64
 17  신호등화순서         613 non-null    object
 18  신호등화시간         613 non-null    object
 19  광원종류           613 non-null    int64
 20  신호제어방식         613 non-null    int64
 21  신호시간결정방식       613 non-null    int64
 22  점멸등운영여부        613 non-null    object
 23  점멸등운영시작시각      613 non-null    object
 24  점멸등운영종료시각      613 non-null    object
 25  보행자작동신호기유무     613 non-null    object
 26  잔여시간표시기유무      613 non-null    object
 27  시각장애인용음향신호기유무  613 non-null    object
 28  도로안내표지일련번호     0 non-null      float64
 29  관리기관명          613 non-null    object
 30  관리기관 전화번호      613 non-null    int64
 31  데이터기준일자        613 non-null    object
dtypes: float64(4), int64(10), object(18)
memory usage: 153.4+ KB

Index(['보호구역 아이디', '시군구명', '도로종류', '도로노선번호', '도로노선명', '도로노선방향', '소재지도로명주소',
       '소재지지번주소', '경도', '위도', '신호기설치방식', '도로형태', '주도로여부', '관리번호', '신호등구분',
       '신호등색종류', '신호등화방식', '신호등화순서', '신호등화시간', '광원종류', '신호제어방식', '신호시간결정방식',
       '점멸등운영여부', '점멸등운영시작시각', '점멸등운영종료시각', '보행자작동신호기유무', '잔여시간표시기유무',
       '시각장애인용음향신호기유무', '도로안내표지일련번호', '관리기관명', '관리기관 전화번호', '데이터기준일자'],
      dtype='object')

In [38]:
signal_df = signal_df[['관리번호','위도','경도']]
signal_df['카테고리'] = '신호등'
signal_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_signal.csv', index=False, encoding='cp949')

In [39]:
# 표지판
# 도로안전표지판 정보는 구할 수 없어, 보호구역내안전표지 정보만 취합함

sign_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내안전표지정보조회.csv', encoding='cp949')
sign_df.info()  
sign_df.head(3)
sign_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   보호구역아이디  371 non-null    int64
 1   시도명      371 non-null    object
 2   시군구명     371 non-null    object
 3   읍면동명     371 non-null    object
 4   관리번호     371 non-null    object
 5   교육시설명칭   371 non-null    object
 6   관할경찰서명   371 non-null    object
 7   위도       371 non-null    float64
 8   경도       371 non-null    float64
 9   데이터기준일자  371 non-null    object
dtypes: float64(2), int64(1), object(7)
memory usage: 29.1+ KB

Index(['보호구역아이디', '시도명', '시군구명', '읍면동명', '관리번호', '교육시설명칭', '관할경찰서명', '위도',
       '경도', '데이터기준일자'],
      dtype='object')

In [40]:
sign_df = sign_df[['관리번호','위도','경도','교육시설명칭']]
sign_df['카테고리'] = '보호구역표지판'
sign_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_sign.csv', index=False, encoding='cp949')

In [41]:
# 보행자용 방호 울타리
fence_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내보행자용방호울타리정보.csv', encoding='cp949')
fence_df.info() 
fence_df.head(3)
fence_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 323 entries, 0 to 322
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   보호구역아이디   323 non-null    int64
 1   시도명       323 non-null    object
 2   시군구명      323 non-null    object
 3   읍면동명      323 non-null    object
 4   도로명       323 non-null    object
 5   소재지도로명주소  323 non-null    object
 6   소재지지번주소   323 non-null    object
 7   관리아이디     323 non-null    object
 8   연장        323 non-null    int64
 9   경도        323 non-null    float64
 10  위도        323 non-null    float64
 11  관리기관명     323 non-null    object
 12  관리기관전화번호  323 non-null    object
 13  데이터기준일자   323 non-null    object
dtypes: float64(2), int64(2), object(10)
memory usage: 35.5+ KB

Index(['보호구역아이디', '시도명', '시군구명', '읍면동명', '도로명', '소재지도로명주소', '소재지지번주소', '관리아이디',
       '연장', '경도', '위도', '관리기관명', '관리기관전화번호', '데이터기준일자'],
      dtype='object')

In [ ]:
fence_df = fence_df[['관리아이디','위도','경도','보호구역아이디']]
fence_df['카테고리'] = '무단횡단방지펜스'
fence_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_fence.csv', index=False, encoding='cp949')

In [43]:
#도로적색표면 정보
red_surface_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내도로적색표면정보.csv', encoding='cp949')
red_surface_df.info()
red_surface_df.head(3)
red_surface_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   보호구역아이디  190 non-null    int64
 1   시도명      190 non-null    object
 2   시군구명     190 non-null    object
 3   읍면동명     190 non-null    object
 4   관리번호     190 non-null    object
 5   교육시설명칭   190 non-null    object
 6   관할경찰서명   190 non-null    object
 7   경도       190 non-null    float64
 8   위도       190 non-null    float64
 9   데이터기준일자  190 non-null    object
dtypes: float64(2), int64(1), object(7)
memory usage: 15.0+ KB

Index(['보호구역아이디', '시도명', '시군구명', '읍면동명', '관리번호', '교육시설명칭', '관할경찰서명', '경도',
       '위도', '데이터기준일자'],
      dtype='object')

In [44]:
red_surface_df = red_surface_df[['관리번호','위도','경도','교육시설명칭']]
red_surface_df['카테고리'] = '도로적색표면'
red_surface_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_red_surface.csv', index=False, encoding='cp949')

In [45]:
#교통단속카메라정보
traffic_camera_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내교통단속카메라정보.csv', encoding='cp949')
traffic_camera_df.info()
traffic_camera_df.head(3)
traffic_camera_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 22 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   보호구역아이디   45 non-null     int64
 1   관리번호      45 non-null     object
 2   시도명       45 non-null     object
 3   시군구명      45 non-null     object
 4   도로종류      45 non-null     object
 5   도로노선번호    0 non-null      float64
 6   도로명       45 non-null     object
 7   도로노선방향    45 non-null     int64
 8   소재지도로명주소  45 non-null     object
 9   소재지지번주소   45 non-null     object
 10  경도        45 non-null     float64
 11  위도        45 non-null     float64
 12  설치장소      45 non-null     object
 13  단속구분      45 non-null     object
 14  제한속도      45 non-null     int64
 15  단속구간위치구분  0 non-null      float64
 16  과속단속구간길이  45 non-null     int64
 17  보호구역구분    45 non-null     object
 18  설치년도      0 non-null      float64
 19  관리기관명     45 non-null     object
 20  관리기관전화번호  45 non-null     int64
 21  데이터기준일자   45 non-null     object
dtypes: float64(5), int64(5), object(12)
memory usage: 7.9+ KB

Index(['보호구역아이디', '관리번호', '시도명', '시군구명', '도로종류', '도로노선번호', '도로명', '도로노선방향',
       '소재지도로명주소', '소재지지번주소', '경도', '위도', '설치장소', '단속구분', '제한속도', '단속구간위치구분',
       '과속단속구간길이', '보호구역구분', '설치년도', '관리기관명', '관리기관전화번호', '데이터기준일자'],
      dtype='object')

In [46]:
traffic_camera_df = traffic_camera_df[['관리번호','위도','경도','제한속도']]
traffic_camera_df['카테고리'] = '무인교통단속카메라'
traffic_camera_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_traffic_camera.csv', index=False, encoding='cp949')

In [47]:
#구할 수 없는 도로안전표지판 대신, 과속방지턱 정보로 대체함
stop_df = pd.read_csv(r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Raw-Data\스쿨존목록 및 안전시설물\광명시보호구역정보\광명시_보호구역내과속방지턱정보.csv', encoding='cp949')
stop_df.info()
stop_df.head(3)
stop_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 23 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   보호구역아이디    249 non-null    int64
 1   관리번호       249 non-null    object
 2   시도명        249 non-null    object
 3   시군구명       249 non-null    object
 4   도로명        249 non-null    object
 5   소재지도로명주소   249 non-null    object
 6   소재지지번주소    249 non-null    object
 7   설치장소       249 non-null    object
 8   과속방지턱재료    249 non-null    int64
 9   과속방지턱형태구분  249 non-null    int64
 10  과속방지턱높이    249 non-null    float64
 11  과속방지턱폭     249 non-null    int64
 12  과속방지턱연장    249 non-null    int64
 13  도로종류       249 non-null    int64
 14  규격여부       249 non-null    object
 15  경도         249 non-null    float64
 16  위도         249 non-null    float64
 17  보차분리여부     249 non-null    object
 18  연속형여부      249 non-null    object
 19  설치년도       0 non-null      float64
 20  관리기관명      249 non-null    object
 21  관리기관전화번호   249 non-null    int64
 22  데이터기준일자    249 non-null    object
dtypes: float64(4), int64(7), object(12)
memory usage: 44.9+ KB

Index(['보호구역아이디', '관리번호', '시도명', '시군구명', '도로명', '소재지도로명주소', '소재지지번주소', '설치장소',
       '과속방지턱재료', '과속방지턱형태구분', '과속방지턱높이', '과속방지턱폭', '과속방지턱연장', '도로종류', '규격여부',
       '경도', '위도', '보차분리여부', '연속형여부', '설치년도', '관리기관명', '관리기관전화번호', '데이터기준일자'],
      dtype='object')

In [48]:
stop_df = stop_df[['관리번호','위도','경도','보호구역아이디']]
stop_df['카테고리'] = '과속방지턱'
stop_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\2_gwangmyung_stop.csv', index=False, encoding='cp949')

### 5. 안전시설물 위치와 보호구역 매칭

In [51]:
import pandas as pd
import glob
import os

# 두 좌표 간 거리 계산 함수 
def haversine_m(lat1, lon1, lat2, lon2):
    """
    두 좌표 사이의 거리를 미터(m) 단위로 반환.
    지구를 구체로 가정하는 Haversine 공식 사용.
    """
    R = 6371000  # 지구 반경 (미터)
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    return R * 2 * np.arcsin(np.sqrt(a))

In [52]:
base_path = r'C:\Users\EL36\Desktop\1차프로젝트_CCTV\1stProject_MSAI09\Preprocessing\광명'
cctv = pd.read_csv(os.path.join(base_path, '2_gwangmyung_cctv.csv'), encoding='cp949')
crosswalk = pd.read_csv(os.path.join(base_path, '2_gwangmyung_crosswalk.csv'), encoding='cp949')
yellow_carpet = pd.read_csv(os.path.join(base_path, '2_gwangmyung_yellow_carpet.csv'), encoding='cp949')
signal = pd.read_csv(os.path.join(base_path, '2_gwangmyung_signal.csv'), encoding='cp949')
sign = pd.read_csv(os.path.join(base_path, '2_gwangmyung_sign.csv'), encoding='cp949')
fence = pd.read_csv(os.path.join(base_path, '2_gwangmyung_fence.csv'), encoding='cp949')
red_surface = pd.read_csv(os.path.join(base_path, '2_gwangmyung_red_surface.csv'), encoding='cp949')
traffic_camera = pd.read_csv(os.path.join(base_path, '2_gwangmyung_traffic_camera.csv'), encoding='cp949')
stop = pd.read_csv(os.path.join(base_path, '2_gwangmyung_stop.csv'), encoding='cp949')

facilities = pd.concat([
    cctv,crosswalk,yellow_carpet,signal,sign,fence,red_surface,traffic_camera,stop],ignore_index=True)
print(facilities['카테고리'].value_counts())
facilities.head(5)

카테고리
신호등          613
보호구역표지판      371
무단횡단방지펜스     323
횡단보도         320
과속방지턱        249
도로적색표면       190
생활안전CCTV      98
무인교통단속카메라     45
옐로카펫          20
Name: count, dtype: int64

,ID_PRT,위도,경도,INST_PURPS,카테고리,관리번호,차로수,교육시설명,교육시설명칭,관리아이디,보호구역아이디,제한속도
0,0020-V-0001,37.465623,126.881458,어린이보호,생활안전CCTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0021-V-0003,37.448624,126.888017,다목적,생활안전CCTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0011-V-0001,37.457696,126.880495,다목적,생활안전CCTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0038-V-0001,37.455972,126.882182,어린이보호,생활안전CCTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0011-V-0002,37.458010,126.880105,다목적,생활안전CCTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
# 스쿨존별로 300m 이내 시설물 개수 카운트

RADIUS = 300  # 미터
categories = facilities['카테고리'].unique()
school_coordinates = school_df[['대상시설명','위도','경도']].drop_duplicates()

results = []

for _, school in school_coordinates.iterrows():
    # 해당 학교와 모든 시설물 간 거리 벡터 계산
    distances = haversine_m(
        school['위도'], school['경도'],
        facilities['위도'].values,
        facilities['경도'].values
    )
    
    # 300m 이내 시설물만 필터
    nearby = facilities[distances <= RADIUS]
    
    # 카테고리별 카운트
    counts = nearby['카테고리'].value_counts()
    
    row = {'시설물명': school['대상시설명'], '위도': school['위도'], '경도': school['경도']}
    for cat in categories:
        row[cat] = counts.get(cat, 0)
    
    results.append(row)

result_df = pd.DataFrame(results)
result_df

,시설물명,위도,경도,생활안전CCTV,횡단보도,옐로카펫,신호등,보호구역표지판,무단횡단방지펜스,도로적색표면,무인교통단속카메라,과속방지턱
0,빛가온초등학교,37.413690,126.882026,8,30,1,47,0,19,13,2,10
1,빛가온유치원,37.416952,126.888265,0,10,0,35,0,12,4,0,1
2,광명생명숲어린이집,37.432309,126.877817,2,6,0,11,0,0,0,0,2
3,큰별어린이집,37.436146,126.877327,0,1,0,7,0,9,3,1,2
4,충현초등학교,37.432490,126.884627,2,14,1,30,0,0,7,2,7
5,트인아이유치원,37.434968,126.886029,2,10,1,11,0,0,3,1,7
6,아란유치원,37.437262,126.879689,2,3,1,12,0,11,4,2,6
7,서면초등학교,37.438660,126.879511,2,3,1,12,0,11,4,2,4
8,광명푸른숲어린이집,37.477792,126.850856,6,2,0,8,0,0,5,3,9
9,예림유치원,37.468770,126.852730,3,11,4,12,0,5,6,2,14
10,예크어린이집,37.469854,126.855135,3,4,3,7,0,0,1,1,5
11,엄지창의어린이집,37.475695,126.849686,5,2,0,2,0,0,4,2,9
12,녹야유치원,37.479271,126.857819,2,8,0,0,0,3,3,1,8
13,광명초등학교,37.480583,126.858215,2,8,0,0,0,3,3,1,8
14,광명남초등학교,37.476247,126.852962,6,2,0,8,0,1,5,3,5
15,광명서초등학교,37.477852,126.847358,7,4,2,0,0,4,4,1,12
16,광문초등학교,37.467075,126.851639,3,10,1,9,0,5,7,2,11
17,광일초등학교,37.471017,126.847025,6,11,0,10,0,16,4,2,20
18,세교유치원,37.420024,126.848711,0,0,0,0,0,0,0,0,0
19,온신초등학교,37.442702,126.845735,2,4,0,0,0,6,3,1,9
20,안서초등학교,37.402054,126.871781,2,2,0,4,0,2,5,0,4
21,산들유치원,37.454875,126.860018,2,1,0,0,0,0,0,0,4
22,하안남초등학교,37.461014,126.885383,2,7,2,23,0,5,3,3,1
23,예솔유치원,37.456700,126.878411,3,12,0,16,0,17,8,2,10
24,구름산유치원,37.455660,126.882186,4,22,0,22,0,21,6,0,9
25,가림초등학교,37.458199,126.880148,3,13,0,16,0,19,8,2,12
26,연서초등학교,37.466264,126.880935,3,10,0,20,0,11,6,2,9
27,파랑새유치원,37.461323,126.881383,1,7,1,10,0,5,2,1,10
28,구름산초등학교,37.453766,126.884436,4,21,3,41,0,23,10,2,6
29,소하초등학교,37.447117,126.888054,5,32,0,93,0,19,16,4,13
30,홍익어린이집,37.474169,126.864569,5,17,0,40,0,15,10,1,9
31,마리아어린이집,37.471791,126.865684,5,32,1,77,0,40,19,2,13
32,광덕초등학교,37.472942,126.867568,5,26,1,69,0,32,15,2,8
33,안현초등학교,37.470454,126.868185,3,25,1,60,0,41,17,2,10
34,구름산어린이집,37.468179,126.865305,1,17,0,17,0,21,12,0,16
35,하안북초등학교,37.465514,126.867289,2,13,0,25,0,18,11,2,10
36,가림유치원,37.463910,126.868203,3,12,0,19,0,15,9,2,8
37,하안초등학교,37.463744,126.874383,2,5,0,8,0,12,5,2,10
38,예원유치원,37.461271,126.877312,2,1,0,4,0,8,4,0,5
39,예지유치원,37.490202,126.867908,2,12,0,13,0,8,5,1,8
40,광명북초등학교,37.487368,126.868001,3,11,0,17,0,14,7,1,10
41,삼흥유치원,37.477651,126.868859,1,1,1,0,0,2,3,0,4
42,혜성유치원,37.466839,126.879238,4,12,0,22,0,15,7,2,11
43,철산초등학교,37.469846,126.873334,4,18,1,53,0,34,12,4,7
44,하일초등학교,37.469302,126.876139,4,16,1,43,0,20,11,4,6
45,한마음유치원,37.467166,126.875826,5,15,1,40,0,28,10,3,8
46,광성초등학교,37.477603,126.872541,4,6,4,12,0,6,7,2,7
47,광명동초등학교,37.483390,126.863980,4,3,0,1,0,9,4,1,11
48,철산어린이집,37.482189,126.862268,4,3,0,1,0,9,4,1,10

In [54]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   시설물명       49 non-null     object
 1   위도         49 non-null     float64
 2   경도         49 non-null     float64
 3   생활안전CCTV   49 non-null     int64
 4   횡단보도       49 non-null     int64
 5   옐로카펫       49 non-null     int64
 6   신호등        49 non-null     int64
 7   보호구역표지판    49 non-null     int64
 8   무단횡단방지펜스   49 non-null     int64
 9   도로적색표면     49 non-null     int64
 10  무인교통단속카메라  49 non-null     int64
 11  과속방지턱      49 non-null     int64
dtypes: float64(2), int64(9), object(1)
memory usage: 4.7+ KB

In [55]:
# 결과 검증 - 시설물 수, 스쿨존 수, 스쿨존별 시설물 수 총합이 일치하는지 확인
# 일치하지 않아 당황했으나..! 초등학교 부설 유치원, 인근 어린이집 등도 스쿨존으로 지정되어 있어, 시설물 수가 스쿨존별 시설물 수 총합보다 많을 수 있음   
print(f"총 시설물 수: {len(facilities)}")
print(f"총 스쿨존 수: {len(school_coordinates)}")
print(f"총 스쿨존별 시설물 수: {result_df[categories].sum().sum()}")

총 시설물 수: 2229
총 스쿨존 수: 49
총 스쿨존별 시설물 수: 3057

In [68]:
result_df.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\1_gwangmyung_facility_counts.csv', index=False, encoding='cp949')

### 6. 모든 데이터 통합

In [87]:
final_schoolzone_df = pd.read_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\0_gwangmyung_school_zone.csv', encoding='cp949')
final_accidents_df = pd.read_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\1_gwangmyung_accidents.csv', encoding='cp949')
final_population_df = pd.read_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\1_gwangmyung_population.csv', encoding='cp949')
final_facility_counts_df = pd.read_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\광명\\1_gwangmyung_facility_counts.csv', encoding='cp949')

In [88]:
final_schoolzone_df.columns

Index(['보호구역아이디', '시설종류', '대상시설명', '소재지도로명주소', '소재지지번주소', '위도', '경도',
       '보호구역 도로폭'],
      dtype='object')

In [89]:
final_accidents_df.columns

Index(['시군명', '구/읍면동명', '사고년도', '발생건수', '사상자수', '사망자수', '중상자수', '경상자수', '부상자수',
       '위도', '경도', '보호구역명'],
      dtype='object')

In [90]:
final_population_df.columns

Index(['동', '총인구수', '0~4세', '5~9세', '10~14세', '어린이 총인구', '어린이 비율(%)'], dtype='object')

In [91]:
final_facility_counts_df.columns

Index(['시설물명', '위도', '경도', '생활안전CCTV', '횡단보도', '옐로카펫', '신호등', '보호구역표지판',
       '무단횡단방지펜스', '도로적색표면', '무인교통단속카메라', '과속방지턱'],
      dtype='object')

In [92]:
#facility 컬럼 순서 정비
final_facility_counts_df = final_facility_counts_df[['시설물명', '위도', '경도','과속방지턱','도로적색표면',
                                                     '무단횡단방지펜스','무인교통단속카메라','보호구역표지판','생활안전CCTV',
                                                     '신호등','옐로카펫','횡단보도']]
final_facility_counts_df.head(3)

,시설물명,위도,경도,과속방지턱,도로적색표면,무단횡단방지펜스,무인교통단속카메라,보호구역표지판,생활안전CCTV,신호등,옐로카펫,횡단보도
0,빛가온초등학교,37.413690,126.882026,10,13,19,2,0,8,47,1,30
1,빛가온유치원,37.416952,126.888265,1,4,12,0,0,0,35,0,10
2,광명생명숲어린이집,37.432309,126.877817,2,0,0,0,0,2,11,0,6

In [93]:
#accident 데이터 정비
final_accidents_df = final_accidents_df.rename(columns={'보호구역명': '시설물명'})
final_accidents_df['사망및중상자수'] = final_accidents_df['사망자수'] + final_accidents_df['중상자수']
final_accidents_df = final_accidents_df[['시설물명','발생건수','사상자수','사망및중상자수','사망자수','중상자수','경상자수']]
final_accidents_df.head(3)

      시설물명  발생건수  사상자수  사망및중상자수  사망자수  중상자수  경상자수
0    예지유치원     2     2        1     0     1     1
1  광명북초등학교     2     2        1     0     1     1
2    예지유치원     2     2        1     0     1     1

In [94]:
combined1 = final_facility_counts_df.merge(final_accidents_df, on='시설물명', how='left')
combined1 = combined1.fillna(0)  # 사고 데이터가 없는 시설물은 0으로 채움
combined1[['발생건수','사상자수','사망및중상자수','사망자수','중상자수','경상자수']] = combined1[['발생건수','사상자수','사망및중상자수','사망자수','중상자수','경상자수']].astype(int) 
combined1.head(3)

,시설물명,위도,경도,과속방지턱,도로적색표면,무단횡단방지펜스,무인교통단속카메라,보호구역표지판,생활안전CCTV,신호등,옐로카펫,횡단보도,발생건수,사상자수,사망및중상자수,사망자수,중상자수,경상자수
0,빛가온초등학교,37.413690,126.882026,10,13,19,2,0,8,47,1,30,0,0,0,0,0,0
1,빛가온유치원,37.416952,126.888265,1,4,12,0,0,0,35,0,10,0,0,0,0,0,0
2,광명생명숲어린이집,37.432309,126.877817,2,0,0,0,0,2,11,0,6,0,0,0,0,0,0

In [95]:
# 스쿨존에서 행정동 정보 추출하기
final_schoolzone_df['동'] = final_schoolzone_df['소재지지번주소'].str.extract(r'(\S+동)')
final_schoolzone_df['동'].value_counts()

동
하안동     12
광명동     10
철산동     10
소하동      9
일직동      2
가학동      2
노온사동     1
하안1동     1
철산1동     1
하안4동     1
Name: count, dtype: int64

In [96]:
#현재 존재하지 않는 행정동, 번호가 있는 행정동을 현 행정동으로 대체하기
final_schoolzone_df.loc[final_schoolzone_df['동'] == '가학동','동'] = '학온동'
final_schoolzone_df.loc[final_schoolzone_df['동'] == '노온사동','동'] = '학온동'
final_schoolzone_df.loc[final_schoolzone_df['동'] == '하안1동','동'] = '하안동'
final_schoolzone_df.loc[final_schoolzone_df['동'] == '하안4동','동'] = '하안동'
final_schoolzone_df.loc[final_schoolzone_df['동'] == '철산1동','동'] = '철산동'

In [97]:
# 동 기준으로 인구 데이터와 병합하기
combined2 = final_schoolzone_df.merge(final_population_df, on='동', how='left')
combined2.columns

Index(['보호구역아이디', '시설종류', '대상시설명', '소재지도로명주소', '소재지지번주소', '위도', '경도',
       '보호구역 도로폭', '동', '총인구수', '0~4세', '5~9세', '10~14세', '어린이 총인구',
       '어린이 비율(%)'],
      dtype='object')

In [98]:
combined2 = combined2.rename(columns={'대상시설명': '시설물명'})
combined2 = combined2[['시설물명', '보호구역 도로폭', '동', '총인구수', '0~4세', '5~9세', '10~14세', '어린이 총인구', '어린이 비율(%)']]
combined2.head(3)

        시설물명  보호구역 도로폭    동   총인구수  0~4세  5~9세  10~14세  어린이 총인구  어린이 비율(%)
0    빛가온초등학교        12  일직동  21148   851   979    1264     3094  14.630225
1     빛가온유치원        14  일직동  21148   851   979    1264     3094  14.630225
2  광명생명숲어린이집        20  소하동  54145  1089  1725    2722     5536  10.224397

In [99]:
#데이터 최종 병합

combined_final = combined1.merge(combined2, on='시설물명', how='left')
combined_final.columns

Index(['시설물명', '위도', '경도', '과속방지턱', '도로적색표면', '무단횡단방지펜스', '무인교통단속카메라',
       '보호구역표지판', '생활안전CCTV', '신호등', '옐로카펫', '횡단보도', '발생건수', '사상자수', '사망및중상자수',
       '사망자수', '중상자수', '경상자수', '보호구역 도로폭', '동', '총인구수', '0~4세', '5~9세',
       '10~14세', '어린이 총인구', '어린이 비율(%)'],
      dtype='object')

In [100]:
combined_final = combined_final[['시설물명', '위도', '경도', '과속방지턱', '도로적색표면', '무단횡단방지펜스', '무인교통단속카메라',
       '보호구역표지판', '생활안전CCTV', '신호등', '옐로카펫', '횡단보도', '보호구역 도로폭', '발생건수', '사상자수', '사망및중상자수', '사망자수', '중상자수', '경상자수',
       '동', '총인구수', '0~4세', '5~9세', '10~14세', '어린이 총인구',
       '어린이 비율(%)']]

combined_final.to_csv('C:\\Users\\EL36\\Desktop\\1차프로젝트_CCTV\\1stProject_MSAI09\\Preprocessing\\5_gwangmyung_final_dataset.csv', index=False, encoding='cp949' )